import React from 'react';
import './css/PrivacyPolicy.css'; 

const PrivacyPolicy = () => {
  return (
    <div className="privacy-container">
      <h1 className="privacy-title">Privacy Policy</h1>

      <p className="privacy-paragraph">
        Welcome to Rebol cab! This Privacy Policy for Rebol cab / Rebol cab
        driver, accessible from [rebolcabs.com](http://rebolcabs.com), explains
        how we collect, safeguard, and disclose information that results from your
        use of our Service.
      </p>

      <h2 className="privacy-subtitle">Location Permissions Policies</h2>
      <p className="privacy-paragraph">
        Our App: Rebol cab takes live location permission with "Background &
        Foreground" Permission access. As a Rebol cab application, to operate
        all the features and functions smoothly, we need to take all these
        permissions from users. If a user doesn't allow all these permissions
        to the application, some of the features of the application will not
        work. So you need to allow the location permission. Rebol cab takes
        your location access to work the application features; we are not
        using your location permission access apart from the application
        features. Rebol cab also never shares any personal content with
        anyone; your data and content are completely secured. You don't need
        to give any other permissions to the application. The location
        permission we need to provide the nearest driver to you as per your
        current location based.
      </p>

      <h2 className="privacy-subtitle">Contact List Permissions Policies</h2>
      <p className="privacy-paragraph">
        Our App: "Rebol cab / Rebol cab driver app" takes permission for the
        contact list. Our "Rebol cab / Rebol cab driver app" provides an SOS
        facility in the app for both the user side and driver side. The feature
        allows both the user and driver to make an emergency call to a number
        that is set up in the list of SOS. Users and drivers can both add
        contact numbers (mobile numbers) from their mobile contact list. To
        do so, they need to give permission for the contact list. Once they
        allow the permission, then they will be able to add their relatives,
        friends, or any other person's number who will help them for emergency
        conditions. They can also give a call to the admin or the Rebol cab /
        Rebol cab driver team. For example, you are a rider and sending a
        parcel from one place to another place by using "Rebol cab / Rebol cab
        driver app", and you feel something insecure; then our app "Rebol cab
        / Rebol cab driver" allows you to make an emergency call in just a
        single click. To call your relative or your known person, you can add
        their mobile number or contact number in the SOS list. For that
        feature, our app "Rebol cab / Rebol cab driver" needs to take access
        of your contact list permission. Once you allow the contact list
        permission to our app, then you will be able to add mobile numbers
        from your contact list to the SOS list. And, in the emergency
        condition, you can call that person in a single click.
      </p>

      <p className="privacy-paragraph">
        We use your data to provide and improve the Service. By using the
        Service, you agree to the collection and use of information in
        accordance with this policy. Unless otherwise defined in this Privacy
        Policy, the terms used in this Privacy Policy have the same meanings
        as in our Terms and Conditions. Our Terms and Conditions (“Terms”)
        govern all use of our Service and, together with the Privacy Policy,
        constitutes your agreement with us (“agreement”).
      </p>

      <h2 className="privacy-subtitle">Definitions</h2>
      <ul className="privacy-list">
        <li className="privacy-list-item">
          <b>SERVICE</b> means the Rebol cab.Raunix.com website operated by
          Rebol cab.Raunix.com
        </li>
        <li className="privacy-list-item">
          <b>PERSONAL DATA</b> means data about a living individual who can
          be identified from those data (or from those and other information
          either in our possession or likely to come into our possession).
        </li>
        <li className="privacy-list-item">
          <b>USAGE DATA</b> is data collected automatically either
          generated by the use of the Service or from the Service infrastructure
          itself (for example, the duration of a page visit).
        </li>
        <li className="privacy-list-item">
          <b>COOKIES</b> are small files stored on your device (computer or
          mobile device).
        </li>
        <li className="privacy-list-item">
          <b>DATA CONTROLLER</b> means a natural or legal person who (either
          alone or jointly or in common with other persons) determines the
          purposes for which and the manner in which any personal data are, or
          are to be, processed. For the purpose of this Privacy Policy, we are
          a Data Controller of your data.
        </li>
        <li className="privacy-list-item">
          <b>DATA PROCESSORS (OR SERVICE PROVIDERS)</b> means any natural
          or legal person who processes the data on behalf of the Data
          Controller. We may use the services of various Service Providers in
          order to process your data more effectively.
        </li>
        <li className="privacy-list-item">
          <b>DATA SUBJECT</b> is any living individual who is the subject of
          Personal Data.
        </li>
        <li className="privacy-list-item">
          <b>THE USER</b> is the individual using our Service. The User
          corresponds to the Data Subject, who is the subject of Personal
          Data.
        </li>
      </ul>

      <h2 className="privacy-subtitle">Information Collection and Use</h2>
      <p className="privacy-paragraph">
        We collect several different types of information for various
        purposes to provide and improve our Service to you.
      </p>

      <h2 className="privacy-subtitle">Types of Data Collected</h2>
      <h3>Personal Data</h3>
      <p className="privacy-paragraph">
        While using our Service, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you (“Personal Data”). Personally identifiable information
        may include, but is not limited to:
      </p>
      <ul className="privacy-list">
        <li className="privacy-list-item">0.1. Email address</li>
        <li className="privacy-list-item">0.2. First name and last name</li>
        <li className="privacy-list-item">0.3. Phone number</li>
        <li className="privacy-list-item">
          0.4. Address, Country, State, Province, ZIP/Postal code, City
        </li>
        <li className="privacy-list-item">0.5. Cookies and Usage Data</li>
      </ul>
      <p className="privacy-paragraph">
        We may use your Personal Data to contact you with newsletters,
        marketing or promotional materials, and other information that may
        be of interest to you. You may opt out of receiving any, or all, of
        these communications from us by following the unsubscribe link.
      </p>

      <h3>Usage Data</h3>
      <p className="privacy-paragraph">
        We may also collect information that your browser sends whenever
        you visit our Service or when you access the Service by or through
        any device (“Usage Data”). This Usage Data may include information
        such as your computer’s Internet Protocol address (e.g., IP address),
        browser type, browser version, the pages of our Service that you
        visit, the time and date of your visit, the time spent on those
        pages, unique device identifiers, and other diagnostic data.
      </p>

      <p className="privacy-paragraph">
        When you access the Service with a device, this Usage Data may
        include information such as the type of device you use, your device
        unique ID, the IP address of your device, your device operating
        system, the type of Internet browser you use, unique device
        identifiers, and other diagnostic data.
      </p>

      <h3>Location Data</h3>
      <p className="privacy-paragraph">
        We may use and store information about your location if you give
        us permission to do so (“Location Data”). We use this data to
        provide features of our Service, to improve and customize our
        Service. You can enable or disable location services when you use
        our Service at any time by way of your device settings.
      </p>

      <h3>Tracking Cookies Data</h3>
      <p className="privacy-paragraph">
        We use cookies and similar tracking technologies to track the
        activity on our Service and hold certain information. Cookies are
        files with a small amount of data which may include an anonymous
        unique identifier. Cookies are sent to your browser from a website
        and stored on your device. Other tracking technologies are also
        used such as beacons, tags, and scripts to collect and track
        information and to improve and analyze our Service.
      </p>

      <p className="privacy-paragraph">
        You can instruct your browser to refuse all cookies or to indicate
        when a cookie is being sent. However, if you do not accept cookies,
        you may not be able to use some portions of our Service.
      </p>

      <p className="privacy-paragraph">
        Examples of Cookies we use:
      </p>

      <ul className="privacy-list">
        <li className="privacy-list-item">0.1. Session Cookies</li>
        <li className="privacy-list-item">0.2. Preference Cookies</li>
        <li className="privacy-list-item">0.3. Security Cookies</li>
        <li className="privacy-list-item">0.4. Advertising Cookies</li>
      </ul>

      <h3>Other Data</h3>
      <p className="privacy-paragraph">
        While using our Service, we may also collect the following
        information: sex, age, date of birth, place of birth, passport
        details, citizenship, registration at place of residence and actual
        address, telephone number (work, mobile), details of documents on
        education, qualification, professional training, employment
        agreements, NDA agreements, information on bonuses and
        compensation, information on marital status, family members, social
        security (or other taxpayer identification) number, office location,
        and other data.
      </p>

      <h2 className="privacy-subtitle">Use of Data</h2>
      <p className="privacy-paragraph">
        Rebol cab.Raunix.com uses the collected data for various
        purposes:
      </p>

      <ul className="privacy-list">
        <li className="privacy-list-item">0.1. to provide and maintain our Service</li>
        <li className="privacy-list-item">
          0.2. to notify you about changes to our Service
        </li>
        <li className="privacy-list-item">
          0.3. to allow you to participate in interactive features of our
          Service when you choose to do so
        </li>
        <li className="privacy-list-item">0.4. to provide customer support</li>
        <li className="privacy-list-item">
          0.5. to gather analysis or valuable information so that we can
          improve our Service
        </li>
        <li className="privacy-list-item">0.6. to monitor the usage of our Service</li>
        <li className="privacy-list-item">
          0.7. to detect, prevent, and address technical issues
        </li>
        <li className="privacy-list-item">
          0.8. to fulfill any other purpose for which you provide it
        </li>
        <li className="privacy-list-item">
          0.9. to carry out our obligations and enforce our rights arising
          from any contracts entered into between you and us, including for
          billing and collection
        </li>
        <li className="privacy-list-item">
          0.10. to provide you with notices about your account and/or
          subscription, including expiration and renewal notices,
          email-instructions, etc.
        </li>
        <li className="privacy-list-item">
          0.11. to provide you with news, special offers, and general
          information about other goods, services, and events which we
          offer that are similar to those that you have already purchased or
          enquired about, unless you have opted not to receive such
          information
        </li>
        <li className="privacy-list-item">
          0.12. in any other way we may describe when you provide the
          information
        </li>
        <li className="privacy-list-item">
          0.13. for any other purpose with your consent
        </li>
      </ul>

      <h2 className="privacy-subtitle">Retention of Data</h2>
      <p className="privacy-paragraph">
        We will retain your Personal Data only for as long as is necessary
        for the purposes set out in this Privacy Policy. We will retain and
        use your Personal Data to the extent necessary to comply with our
        legal obligations (for example, if we are required to retain your
        data to comply with applicable laws), resolve disputes, and enforce
        our legal agreements and policies. We will also retain Usage Data
        for internal analysis purposes. Usage Data is generally retained
        for a shorter period, except when this data is used to strengthen
        the security or to improve the functionality of our Service, or we
        are legally obligated to retain this data for longer time periods.
      </p>

      <h2 className="privacy-subtitle">Transfer of Data</h2>
      <p className="privacy-paragraph">
        Your information, including Personal Data, may be transferred to
        – and maintained on – computers located outside of your state,
        province, country, or other governmental jurisdiction where the
        data protection laws may differ from those of your jurisdiction. If
        you are located outside India and choose to provide information to
        us, please note that we transfer the data, including Personal
        Data, to India and process it there. Your consent to this Privacy
        Policy followed by your submission of such information represents
        your agreement to that transfer. Rebol cab.Raunix.com will take
        all the steps reasonably necessary to ensure that your data is
        treated securely and in accordance with this Privacy Policy and no
        transfer of your Personal Data will take place to an organisation
        or a country unless there are adequate controls in place including
        the security of your data and other personal information.
      </p>

      <h2 className="privacy-subtitle">Disclosure of Data</h2>
      <p className="privacy-paragraph">
        We may disclose personal information that we collect, or you
        provide:
      </p>

      <ul className="privacy-list">
        <li className="privacy-list-item">
          0.1. Disclosure for Law Enforcement. Under certain
          circumstances, we may be required to disclose your Personal
          Data if required to do so by law or in response to valid requests
          by public authorities.
        </li>
        <li className="privacy-list-item">
          0.2. Business Transaction. If we or our subsidiaries are
          involved in a merger, acquisition, or asset sale, your Personal
          Data may be transferred.
        </li>
        <li className="privacy-list-item">
          0.3. Other cases. We may disclose your information also:
        </li>
        <li className="privacy-list-item">0.3.1. to our subsidiaries and affiliates</li>
        <li className="privacy-list-item">
          0.3.2. to contractors, service providers, and other third
          parties we use to support our business
        </li>
        <li className="privacy-list-item">
          0.3.3. to fulfill the purpose for which you provide it
        </li>
        <li className="privacy-list-item">
          0.3.4. for the purpose of including your company’s logo on
          our website
        </li>
        <li className="privacy-list-item">
          0.3.5. for any other purpose disclosed by us when you
          provide the information
        </li>
        <li className="privacy-list-item">0.3.6. with your consent in any other cases</li>
        <li className="privacy-list-item">
          0.3.7. if we believe disclosure is necessary or appropriate
          to protect the rights, property, or safety of the Company, our
          customers, or others.
        </li>
      </ul>

      <h2 className="privacy-subtitle">Security of Data</h2>
      <p className="privacy-paragraph">
        The security of your data is important to us, but remember that
        no method of transmission over the Internet or method of
        electronic storage is 100% secure. While we strive to use
        commercially acceptable means to protect your Personal Data, we
        cannot guarantee its absolute security.
      </p>

      <h2 className="privacy-subtitle">
        Your Data Protection Rights Under General Data Protection
        Regulation (GDPR)
      </h2>
      <p className="privacy-paragraph">
        If you are a resident of the European Union (EU) and European
        Economic Area (EEA), you have certain data protection rights,
        covered by GDPR. We aim to take reasonable steps to allow you
        to correct, amend, delete, or limit the use of your Personal
        Data. If you wish to be informed what Personal Data we hold about
        you and if you want it to be removed from our systems, please
        contact us.
      </p>

      <div className="terms-footer">
        <p className="terms-footer-text">
          For general inquiries, complaints, questions or claims concerning the
          licensed Application, please contact:
        </p>
        <address className="terms-footer-address">
          Rebol Cabs
          <br />
          16 h, 8/2, Maruthi Nagar, New Santoshnagar,
          <br />
          Hyderabad, Telangana 500059
          <br />
          India
          <br />
          <strong>Email:</strong>{" "}
          <a href="mailto:info@rebolcabs.in">info@rebolcabs.in</a>
        </address>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
